theme: jekyll-theme-minimal
title: Chandana Karunaratne
description: <b>Data Analyst (Python + SQL)</b> <br><br><b>Contact:&nbsp;</b>[chandana.karu@gmail.com](mailto:chandana.karu@gmail.com)<br><br> <b>Resume:&nbsp;</b><a href="chandana-karunaratne.github.io/RESUME_Chandana_Karunaratne.pdf" target="_blank">Data Analyst_Chandana Karunaratne</a>
google_analytics: UA-162273372-1
github:
  is_project_page: false
