theme: jekyll-theme-minimal
title: Chandana Karunaratne
description: <b>Data Analyst (Python + SQL)</b> <br><br> <b>Contact:&nbsp;</b><a href="mailto:chandana.karu@gmail.com" target="_blank">chandana.karu@gmail.com</a> <br><br> <a href="https://www.linkedin.com/in/chandana-karu/" target="_blank"><b>LinkedIn&emsp;&emsp;&nbsp;</b></a> <a href="chandana-karunaratne.github.io/RESUME_Chandana_Karunaratne.pdf" target="_blank"><b>Resume&emsp;&emsp;&nbsp;</b></a> <a href="https://github.com/chandana-karunaratne" target="_blank"><b>GitHub</b></a>
google_analytics: UA-162273372-1
