theme: jekyll-theme-minimal
title: Chandana Karunaratne
description: Data analyst with MSc in data science and 7+ years of experience in applying statistical analysis to economic and market research. Proven track record of driving employer revenue growth and reducing employee labour costs via development of automated data analytics tools using Python and MySQL.
