theme: jekyll-theme-minimal
title: Chandana Karunaratne
description: Data Analyst (Python + SQL)
**Contact:** <a href="mailto:chandana.karu@gmail.com" target="_blank">chandana.karu@gmail.com</a>

**LinkedIn:** <a href="https://www.linkedin.com/in/chandana-karu/" target="_blank">linkedin.com/in/chandana-karu</a>

**Resume:** <a href="chandana-karunaratne.github.io/RESUME_Chandana_Karunaratne.pdf" target="_blank">Data Analyst_Chandana Karunaratne</a>


google_analytics: UA-162273372-1
